export { default as Navbar } from "./Navbar";
export { default as Header } from "./Header";
export { default as WhatWeCanDo } from "./WhatWeCanDo";
export { default as OurWorks } from "./OurWorks";
export { default as DigitalMarketing } from "./DigitalMarketing";
export { default as Feedback } from "./Feedback";
export { default as Cursor } from "./Cursor";
export { default as WeAreTrusted } from "./WeAreTrusted";
export { default as Loader } from "./Loader";
